name: Build and Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build-test:

    #Gitrunner hosted by Github
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Copy database.yml
      run: cp config/database.yml.sample config/database.yml
    - name: Build speakerinnen Docker image
      run: make setup
    - name: Run all tests
      run: make test
